# Build the docker image and push it to GitHub Packages

name: Coti Ledger App Builder Publisher

on: [workflow_dispatch]

jobs:
  build:
    name: Build and push coti-ledger-app-builder image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build and push coti-ledger-app-builder to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          repository: coti-io/coti-ledger-app-builder
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_sha: true
          tags: latest